### ISSUE TITLE
[Categories]Implement "Sorry, no results found" block 

### ISSUE THREAD

**Issue by RomanKhorol** [WebUI-Project-Based-07-nr/Client#151]
Implement "Sorry, no results found" block that will be displayed if there are no categories matching the search

![Image](https://github.com/user-attachments/assets/dc8f8119-c1d5-4d3c-ba9c-d60f78d88ad4)

- [ ] The block should be displayed if there are no categories matching the search

**Comment by markgol777** [comment]
already exists in the project
